phrase:
  access_token: d3f31c5732d55a42d3098d185800a6ede9d27e75debd27a563f715d5a1d98644
  project_id: 32b61ddb971dc55f15a10417384bb51f
  push:
    sources:
    - file: ./Test_P.php
      params:
        file_format: laravel
        locale_id: English
        update_translations: true
  pull:
    targets:
    - file: ./Test_P_fr.php
      params:
        file_format: laravel
        locale_id: French
        include_empty_translations: true
